"""2nd commit

Revision ID: cd902c44a537
Revises: 63dde6e4b36f
Create Date: 2023-07-07 13:01:19.314721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd902c44a537'
down_revision = '63dde6e4b36f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
