"""3rd commit

Revision ID: ebbfc6e151dd
Revises: cd902c44a537
Create Date: 2023-07-07 13:05:30.329835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbfc6e151dd'
down_revision = 'cd902c44a537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
